version: '3.8'

services:
  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    networks:
      - backend_network

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend_network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend_network

networks:
  backend_network:
