version: '3.4'

services:
  zad1:
    image: zad1
    build:
      context: lab02/zad1
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
