version: '3.4'

services:
  lab02zad1:
    image: lab02zad1
    build:
      context: lab02/zad1
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  lab02zad2:
    image: lab02zad2
    build:
      context: lab02/zad2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  lab02zad3:
    build:
      context: lab02/zad3
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  lab03zad1:
    build:
      context: lab03/zad1
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./lab03/zad1/index.html:/usr/share/nginx/html/index.html
  lab03zad2:
    build:
      context: lab03/zad2
      dockerfile: ./Dockerfile
    ports:
      - 80:81
  lab03zad3-nginx:
    build:
      context: lab03/zad3/nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
  lab03zad3-app:
    container_name: app
    build:
      context: lab03/zad3/app
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000 
  lab04zad1:
    build:
      context: lab04/zad1
      dockerfile: ./Dockerfile
    volumes:
      - nginx_data:/usr/share/nginx/html
  lab04zad2:
    build:
      context: lab04/zad2
      dockerfile: ./Dockerfile
    volumes:
      - node_data:/app
    
volumes:
  nginx_data:
  node_data:
  mongodb:
