version: '3.8'

services:
  lab04zad1:
    build:
      context: zad1
      dockerfile: ./Dockerfile
    volumes:
      - nginx_data:/usr/share/nginx/html
  lab04zad2:
    build:
      context: zad2
      dockerfile: ./Dockerfile
    volumes:
      - node_data:/app

volumes:
  nginx_data:
  node_data: