version: '3.8'

services:
  lab07zad1:
    image: mongo:${MONGO_VERSION}
    container_name: db
    networks:
      - net_A
    volumes:
      - mongodb:/data/db
    ports:
      - ${MONGO_PORT}:27017
  lab07zad2:
    build:
      context: zad2
      dockerfile: ./Dockerfile
    container_name: server
    networks:
      - net_A
    depends_on:
      - lab07zad1
    ports:
      - 3003:3000

networks:
  net_A:
    driver: bridge
    driver_opts:
      parent: en0