version: '3.8'

services:
  lab05zad1:
    build:
      context: zad1
      dockerfile: ./Dockerfile
  lab05zad2:
    build:
      context: zad2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
  lab05zad3:
    build:
      context: zad3
      dockerfile: ./Dockerfile
      args:
        PYTHON_VERSION: 3.11
  lab05zad4:
    build:
      context: zad4
      dockerfile: ./Dockerfile
      args:
        PYTHON_VERSION: 3.10.10-r0
    environment:
      APP_PORT: 8080
      PYTHON_VERSION: 3.10.10-r0
    ports:
      - 8080:8080
    volumes:
      - python_data:/usr/myapp
  lab05zad5:
    build:
      context: zad5
      dockerfile: ./Dockerfile
    ports:
      - 81:81

volumes:
  python_data: