version: '3.8'

services:
  lab09zad1:
    build:
      context: zad1
      dockerfile: ./Dockerfile
    ports:
    - 3000:3000 
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/live || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3